matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
    - os: linux
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libdbus-1-dev -y; fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       yarn run build:linux
    else
       yarn run build:mac
    fi

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
       bash upload.sh Audiation*.AppImage
       bash upload.sh audiation*.deb
    else
       wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
       bash upload Audiation*.dmg
    fi