skip_tags: true

image: Visual Studio 2017

environment:
  nodejs_version: "12.14.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g electron-builder
  - npm i

build_script:
  - npm run electron:build

deploy_script:
- ps: >-
    Start-FileDownload 'https://github.com/probonopd/uploadtool/raw/master/upload.sh'
    
    sh -c "TRAVIS_BRANCH=$env:APPVEYOR_REPO_BRANCH TRAVIS_COMMIT=$env:APPVEYOR_REPO_COMMIT ./upload.sh /c/projects/firetail/dist_electron/Firetail-Setup-0.6.0.exe 2>/dev/null"