name: Continuous

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm i
          npm run electron:build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: true
          TRAVIS_BRANCH: next
          TRAVIS_COMMIT: ${{ github.sha }}
          REPO_SLUG: kawuchuu/firetail
        run: |
          curl https://github.com/probonopd/uploadtool/raw/master/upload.sh --output upload.sh
          bash upload.sh dist_electron/Firetail*.*