name: Continuous

on:
  push:
    branches:
      - next

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Version
        id: package-version
        run: |
          PACKAGE_JSON_PATH="${1-.}"
          PACKAGE_VERSION=$(cat ${PACKAGE_JSON_PATH}/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo ::set-output name=current-version::$PACKAGE_VERSION
      - name: Get Build Number
        id: get-ver-build
        run: |
          build=$(echo ${{ github.sha }} | cut -c1-7)
          echo "::set-output name=build::$build"
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14.17.0'
      - name: Install deps & build artifacts
        run: |
          export FTBUILD_NUM=${{steps.get-ver-build.outputs.build}}
          export BUILD_NUMBER=${{steps.get-ver-build.outputs.build}}
          npm i -g node-gyp@8.4.1
          npm config set msvs_version 2022
          yarn
          yarn electron:build
      - if: matrix.os == 'windows-latest'
        name: Move Windows artifacts to directory
        shell: bash
        run: |
          mkdir dist_electron/artifacts-upload
          mv ./dist_electron/*.exe ./dist_electron/artifacts-upload
      - if: matrix.os == 'macos-latest'
        name: Move macOS artifacts to directory
        shell: bash
        run: |
          mkdir dist_electron/artifacts-upload
          mv ./dist_electron/*.dmg ./dist_electron/artifacts-upload
      - if: matrix.os == 'ubuntu-latest'
        name: Move Linux artifacts to directory
        shell: bash
        run: |
          mkdir dist_electron/artifacts-upload
          mv ./dist_electron/*.rpm ./dist_electron/artifacts-upload
          mv ./dist_electron/*.deb ./dist_electron/artifacts-upload
          mv ./dist_electron/*.AppImage ./dist_electron/artifacts-upload
      - name: Upload artifacts to continuous GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: true
          TRAVIS_BRANCH: next
          TRAVIS_COMMIT: ${{ github.sha }}
          REPO_SLUG: kawuchuu/firetail
        run: |
          curl https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh --output upload.sh
          bash upload.sh dist_electron/artifacts-upload/Firetail*.*
# I don't like how GitHub artifacts work...
#      - name: Upload artifacts to GitHub actions
#        uses: actions/upload-artifact@v2
#        with:
#          name: Firetail ${{steps.get-ver-build.outputs.build}}
#          path: ./dist_electron/artifacts-upload/