name: Continuous

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm i
          npm run electron:build
        
      - name: Get upload tool
        uses: wei/wget@v1
        with:
          args: -c https://github.com/probonopd/uploadtool/raw/master/upload.sh

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: true
          TRAVIS_BRANCH: next
          TRAVIS_COMMIT: $GITHUB_SHA
        run: |
          bash upload.sh dist_electron/Firetail*.*