name: Continuous

on:
  push:
    branches:
      - next

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - id: get-ver-build
        run: |
          build=$(echo ${{ github.sha }} | cut -c1-5)
          echo "::set-output name=build::$build"
      - name: Build
        run: |
          export FTBUILD_NUM=${{steps.get-ver-build.outputs.build}}
          npm i
          bash npm run electron:build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: true
          TRAVIS_BRANCH: next
          TRAVIS_COMMIT: ${{ github.sha }}
          REPO_SLUG: kawuchuu/firetail
        run: |
          curl https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh --output upload.sh
          bash upload.sh dist_electron/Firetail*.*